# Generated by Django 3.0 on 2020-07-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testerapp', '0002_auto_20200727_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='child',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='testerapp.ChildChild'),
        ),
    ]
